// This file is auto-generated by @hey-api/openapi-ts

export type LoginData = {
    body: {
        /**
         * Логин пользователя
         */
        login: string;
        /**
         * Пароль пользователя
         */
        password: string;
    };
};

export type LoginResponse = ({
    /**
     * JWT токен
     */
    token?: string;
});

export type LoginError = (unknown);

export type RegisterData = {
    body: {
        /**
         * Логин пользователя
         */
        login: string;
        /**
         * Пароль пользователя
         */
        password: string;
        /**
         * Email пользователя
         */
        email: string;
        /**
         * Полное имя пользователя
         */
        full_name: string;
    };
};

export type RegisterResponse = ({
    message?: string;
});

export type RegisterError = (unknown);

export type GetProfileResponse = ({
    /**
     * UUID пользователя
     */
    uuid?: string;
    /**
     * Логин пользователя
     */
    login?: string;
    /**
     * Email пользователя
     */
    email?: string;
    /**
     * Полное имя пользователя
     */
    full_name?: string;
});

export type GetProfileError = (unknown);

export type SendFriendRequestData = {
    query: {
        /**
         * Логин друга
         */
        friend_login: string;
    };
};

export type SendFriendRequestResponse = ({
    message?: string;
});

export type SendFriendRequestError = (unknown);

export type AcceptFriendRequestData = {
    query: {
        /**
         * Логин друга
         */
        friend_login: string;
    };
};

export type AcceptFriendRequestResponse = ({
    message?: string;
});

export type AcceptFriendRequestError = (unknown);

export type DeclineFriendRequestData = {
    query: {
        /**
         * Логин друга
         */
        friend_login: string;
    };
};

export type DeclineFriendRequestResponse = ({
    message?: string;
});

export type DeclineFriendRequestError = (unknown);

export type RemoveFriendData = {
    query: {
        /**
         * Логин друга
         */
        friend_login: string;
    };
};

export type RemoveFriendResponse = ({
    message?: string;
});

export type RemoveFriendError = (unknown);

export type SearchUserData = {
    query: {
        /**
         * Количество результатов на странице (по умолчанию 10)
         */
        limit?: number;
        /**
         * Номер страницы (по умолчанию 1)
         */
        page?: number;
        /**
         * Запрос для поиска (логин или имя)
         */
        query: string;
    };
};

export type SearchUserResponse = (Array<{
    /**
     * UUID пользователя
     */
    uuid?: string;
    /**
     * Логин пользователя
     */
    login?: string;
    /**
     * Полное имя пользователя
     */
    full_name?: string;
    /**
     * Email пользователя
     */
    email?: string;
}>);

export type SearchUserError = (unknown);